### ISSUE TITLE
Version management 

### ISSUE THREAD

**Issue by agrohn** [scaepz/SDL-Course#1]
Please use only a single solution for entire course - you can commit all changes on top of previous modules, since version management keeps track of every change, and individual commit can be named using a TAG to indicate which answer it is (say, Module1, Module2, Module3). 

Splitting code into separate directories like you have done is an abuse of version management tool, please stop :)

**Comment by scaepz** [comment]
Okay thankyou. I was wondering this earlier. I will fix it for next module.

**Comment by scaepz** [comment]
Fixed
