### ISSUE TITLE
Wrong header file #include

### ISSUE THREAD

**Issue by agrohn** [scaepz/SDL-Course#4]
This:
```
#include <stdexcpt.h>
```

Should be 
```
#include <stdexcept>
```

C++ standard library does not use `.h` suffices, and their use is not allowed. What strikes me odd, is that even visual studio should have given you an error about the missing header, stdexcpt.h SHOULD not exist, unless you have created that on your own?

**Comment by scaepz** [comment]
I've changed stdexcpt.h to stdexcept, but in case you are curious here is what stdexcpt.h contains:
    /***
    *stdexcpt.h - User include file for standard exception classes
    *
    *       Copyright (c) Microsoft Corporation. All rights reserved.
    *
    *Purpose:
    *       This file is the previous location of the standard exception class
    *       definitions, now found in the standard header <exception>.
    *
    *       [Public]
    *
    ****/

    #pragma once

    #include <crtdefs.h>

    #ifndef _INC_STDEXCPT
    #define _INC_STDEXCPT

    #ifdef __cplusplus

    #include <exception>

    #endif  /* __cplusplus */
    #endif  /* _INC_STDEXCPT */
